version: '2'

services:
  proxy:
    image: traefik
    command: --docker.domain=${DOMAIN} --logLevel=DEBUG
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme/acme.json

  www:
    image: imarcagency/php-apache:2
    environment:
      - "APACHE_ROOT=/var/www/public"
      - "DOMAIN=${DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.${DOMAIN}"
      - "traefik.port=80"
    volumes:
      - "./:/var/www"
      - "./docker-configure.sh:/usr/local/bin/docker-configure"
      - "app_storage:/var/www/storage"

#
#  web:
#    build:
#      context: ./
#      dockerfile: web.dockerfile
#    working_dir: /var/www
#    volumes_from:
#    - app
#    ports:
#    - 8080:80

  mysql:
    image: "mariadb:10.3"
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - "mysql_data:/var/lib/mysql"
#
  redis:
    image: "redis:3.2"
    command: "redis-server --appendonly yes"
    volumes:
      - "redis_data:/data"
#
  pondtemp:
    build: echo
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:echo.${DOMAIN}"
      - "traefik.port=8888"
    working_dir: "/usr/src/app"
    volumes:
      - "./:/usr/src/app"

volumes:
  app_storage:
  mysql_data:
  redis_data:
