language: php

php:
  - 7.1

matrix:
    allow_failures:
        - php: hhvm


before_script:
  - cp .env.travis .env
  - mysql -e 'create database pond_testing;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate

script: vendor/bin/phpunit

cache:
  directories:
    - vendor

services:
  - mysql