version: '3.4'
networks:
  web:
    external: true
  frontend:
    driver: bridge
  backend:
    driver: bridge
    external: false

services:
  app:
    image: redcopy/pond_temp_app:latest
    build:
      dockerfile:  Dockerfile
      context: .

    working_dir: /var/www
    extra_hosts:
    - "mysql:127.0.0.1"

    volumes:
    - database
    - $HOME/.composer/:$HOME/.composer/
    environment:
    - "DB_HOST=database"
    - "DB_DATABASE=homestead"
    - "DB_USERNAME=admin"
    - "DB_PASSWORD=secret"
    #    - "REDIS_HOST=redis"
    #    - "REDIS_PORT=6379"
    expose:
    - "9000"

    networks:
    - backend

  # The Web Server
  web:
    image: redcopy/pond_web:1.00
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
    - app
    ports:
    - 8080:8080
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${DOMAIN}"
    - "traefik.port=80"
    networks:
    - frontend
    - backend
  #  # The Database
  database:
    build:
      context: docker/database
    volumes:
    - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=admin"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    networks:
    - backend

  whoami:
    image: emilevauge/whoami
    labels:
    - "traefik.frontend.rule=Host:whoami.${DOMAIN}"
    networks:
    - frontend
  traefik:
    build:
      context: .
      dockerfile:  docker/traefik/Dockerfile
    command: --docker.domain=${DOMAIN} --logLevel=DEBUG
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #    - .traefik/traefik.toml:/traefik.toml
    #    - .traefik/acme.json:/acme.json
    #
    #    - ./docker/traefik/traefik.toml:/traefik.toml
    #    - ./docker/traefik/acme.json:/acme.json
    container_name: pondtemp_traefik
    networks:
    - backend
    - frontend

  pondtemp-consul:
    image: progrium/consul
    command: -server -bootstrap -log-level debug -ui-dir /ui
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    expose:
    - "8300"
    - "8301"
    - "8301/udp"
    - "8302"
    - "8302/udp"

#    whoami1:
#      image: emilevauge/whoami
#
#    whoami2:
#      image: emilevauge/whoami
#
#    whoami3:
#      image: emilevauge/whoami
#
#    whoami4:
#      image: emilevauge/whoami
    networks:
    - frontend
