version: '3'
networks:
  web:
    external: true
  frontend:
    driver: bridge
  backend:
    driver: bridge
    external: false

services:
  app:
    image: redcopy/pond_temp_app:latest
    build:
      dockerfile:  Dockerfile
      context: .

    working_dir: /var/www
    env_file: '.env'
    extra_hosts:
    - "mysql:127.0.0.1"

    volumes:
    - database
    - $HOME/.composer/:$HOME/.composer/
    environment:
    - "DB_HOST=database"
    - "DB_DATABASE=homestead"
    - "DB_USERNAME=admin"
    - "DB_PASSWORD=secret"
    #    - "REDIS_HOST=redis"
    #    - "REDIS_PORT=6379"
    expose:
    - "9000"

    networks:
    - backend

  # The Web Server
  web:
    image: redcopy/pond_web:1.00
    env_file: .env
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
    - app
    ports:
    - 8080:8080
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:dokersto.test"
    - "traefik.port=80"
    networks:
    - frontend
    - backend
  #  # The Database
  database:
    build:
      context: docker/database
    volumes:
    - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=admin"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    networks:
    - backend


  traefik:
    build:
      dockerfile:  docker/traefik/Dockerfile
      context: .
    env_file: .env
    command: --docker.domain=${APP_URL} --logLevel=DEBUG
    restart: always
    ports:
    - 80:80
    - 443:443
    networks:
    - backend
    - frontend
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/traefik.toml:/traefik.toml
    - ./traefik/acme.json:/acme.json
    container_name: pondtemp_traefik

