version: '3'

# Instantiate your own configuration with a Dockerfile!
# This way you can build somewhere and just deploy your container
# anywhere without the need to copy files around.
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  app:
    image: redcopy/pond_temp_app:latest
    build:
      dockerfile:  ../Dockerfile
      context: ../
    working_dir: /var/www
    extra_hosts:
    - "mysql:127.0.0.1"

    volumes:
    - database
#    - ../:/var/www/
    - $HOME/.composer/:$HOME/.composer/
    environment:
    - "DB_HOST=database"
    - "DB_DATABASE=homestead"
    - "DB_USERNAME=admin"
    - "DB_PASSWORD=secret"
#    - "REDIS_HOST=redis"
#    - "REDIS_PORT=6379"
    expose:
     - "9000"

    networks:
    - backend
#  # The Web Server
  web:
    image: redcopy/pond_web:1.00
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
       - app
    ports:
     - 80:80
    networks:
     - frontend
     - backend
  #  # The Database
  database:
    build:
      context: ./database
    volumes:
#      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=admin"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    networks:
     - backend
#
