version: '2'
services:

  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=homestead"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    ports:
    - "33061:3306"

volumes:
  dbdata:
  view raw